// ─── HARDCODED NGOs ───────────────────────────────────────────────────
export const MOCK_NGOS: Record<string, any> = {
  'shiksha-foundation': {
    id: 'shiksha-foundation',
    name: 'Shiksha Foundation',
    darpan_id: 'MH/2018/0187432',
    category: 'Education',
    city: 'Chennai',
    transparency_score: 87,
    status: 'VERIFIED',
    description: 'Empowering underprivileged children across Tamil Nadu through quality education, books, and trained volunteer teachers.',
    total_donations: 1420000,
    donor_count: 312,
    complaint_count: 2,
    founded: '2018',
    website: 'https://shikshatn.org',
    web_sources: [
      { id: 'ws1', label: 'The Hindu coverage', url: 'https://thehindu.com/education/shiksha', type: 'News Coverage', domain: 'thehindu.com', credibility: 'High Credibility', date: '2025-11-12' },
      { id: 'ws2', label: 'Govt recognition letter', url: 'https://tn.gov.in/ngo/shiksha', type: 'Government Mention', domain: 'tn.gov.in', credibility: 'High Credibility', date: '2025-09-01' },
    ],
  },
  'pragati-path': {
    id: 'pragati-path',
    name: 'Pragati Path',
    darpan_id: 'DL/2019/0234521',
    category: 'Education',
    city: 'Mumbai',
    transparency_score: 72,
    status: 'VERIFIED',
    description: 'Bridging the digital divide for students in rural Maharashtra through tablets, digital classrooms, and tech literacy programs.',
    total_donations: 980000,
    donor_count: 187,
    complaint_count: 5,
    founded: '2019',
    website: 'https://pragatipath.in',
    web_sources: [
      { id: 'ws3', label: 'Times of India article', url: 'https://timesofindia.com/pragati', type: 'News Coverage', domain: 'timesofindia.com', credibility: 'High Credibility', date: '2025-10-20' },
    ],
  },
  'annamayya-trust': {
    id: 'annamayya-trust',
    name: 'Annamayya Trust',
    darpan_id: 'TN/2017/0156789',
    category: 'Food/Hunger',
    city: 'Delhi',
    transparency_score: 91,
    status: 'VERIFIED',
    description: 'Running community kitchens and monthly ration drives for homeless populations in Delhi, serving 500+ meals daily.',
    total_donations: 2350000,
    donor_count: 540,
    complaint_count: 0,
    founded: '2017',
    website: 'https://annamayya.org',
    web_sources: [
      { id: 'ws4', label: 'NDTV feature segment', url: 'https://ndtv.com/annamayya', type: 'News Coverage', domain: 'ndtv.com', credibility: 'High Credibility', date: '2026-01-15' },
      { id: 'ws5', label: 'Municipal Corp MoU', url: 'https://mcdonline.nic.in/annamayya', type: 'Government Mention', domain: 'nic.in', credibility: 'High Credibility', date: '2025-08-10' },
    ],
  },
  'nourish-the-nation': {
    id: 'nourish-the-nation',
    name: 'Nourish The Nation',
    darpan_id: 'KA/2020/0298341',
    category: 'Food/Hunger',
    city: 'Bangalore',
    transparency_score: 65,
    status: 'UNDER_REVIEW',
    description: 'Providing monthly ration kits to migrant worker families in Bangalore with a focus on nutrition and food security.',
    total_donations: 510000,
    donor_count: 98,
    complaint_count: 12,
    founded: '2020',
    website: 'https://nourishemnation.in',
    web_sources: [
      { id: 'ws6', label: 'Medium blog post', url: 'https://medium.com/nourish-nation', type: 'Social Media', domain: 'medium.com', credibility: 'Unverified Source', date: '2025-12-02' },
    ],
  },
  'aarogya-health-mission': {
    id: 'aarogya-health-mission',
    name: 'Aarogya Health Mission',
    darpan_id: 'MH/2016/0123456',
    category: 'Healthcare',
    city: 'Chennai',
    transparency_score: 94,
    status: 'VERIFIED',
    description: 'Deploying mobile medical units to rural Tamil Nadu, conducting health camps, and providing medicines to 300+ patients monthly.',
    total_donations: 3800000,
    donor_count: 721,
    complaint_count: 1,
    founded: '2016',
    website: 'https://aarogyatn.org',
    web_sources: [
      { id: 'ws7', label: 'WHO recognition', url: 'https://who.int/india/aarogya', type: 'Government Mention', domain: 'who.int', credibility: 'High Credibility', date: '2025-07-22' },
      { id: 'ws8', label: 'Indian Express report', url: 'https://indianexpress.com/aarogya', type: 'News Coverage', domain: 'indianexpress.com', credibility: 'High Credibility', date: '2026-02-01' },
    ],
  },
  'vriksh-protectors': {
    id: 'vriksh-protectors',
    name: 'Vriksh Protectors',
    darpan_id: 'DL/2021/0345678',
    category: 'Environment',
    city: 'Delhi',
    transparency_score: 58,
    status: 'UNDER_REVIEW',
    description: 'Planting native saplings in Delhi-NCR degraded land areas and organizing community-led green drives for sustainable urban forestry.',
    total_donations: 275000,
    donor_count: 63,
    complaint_count: 15,
    founded: '2021',
    website: 'https://vrikshprotectors.in',
    web_sources: [
      { id: 'ws9', label: 'Instagram reel', url: 'https://instagram.com/vrikshprotectors', type: 'Social Media', domain: 'instagram.com', credibility: 'Unverified Source', date: '2026-01-05' },
    ],
  },
};

// ─── DARPAN ID → NGO ID MAP ───────────────────────────────────────────
export const DARPAN_MAP: Record<string, string> = {
  'MH/2018/0187432': 'shiksha-foundation',
  'DL/2019/0234521': 'pragati-path',
  'TN/2017/0156789': 'annamayya-trust',
  'KA/2020/0298341': 'nourish-the-nation',
  'MH/2016/0123456': 'aarogya-health-mission',
  'DL/2021/0345678': 'vriksh-protectors',
};

export const NGO_LIST = Object.values(MOCK_NGOS);

// ─── HARDCODED MILESTONES ─────────────────────────────────────────────
export const MOCK_MILESTONES: Record<string, any[]> = {
  'shiksha-foundation': [
    { id: 'sf-m1', title: 'Purchase textbooks for 200 students', description: 'Buy grade-appropriate textbooks and distribute to 200 underprivileged students in partner schools.', amount_locked: 25000, status: 'UNLOCKED', required_proof: 'Photo of books distributed to children with teacher signatures' },
    { id: 'sf-m2', title: 'Set up reading corners in 3 classrooms', description: 'Install bookshelves, cushions, and reading material to create dedicated reading areas.', amount_locked: 25000, status: 'LOCKED', required_proof: 'Before/after photo of all 3 classroom reading corners' },
    { id: 'sf-m3', title: 'Train 10 volunteer teachers', description: 'Conduct a 3-day workshop for 10 volunteer teachers on inclusive education techniques.', amount_locked: 25000, status: 'LOCKED', required_proof: 'Group photo of trained volunteers with completion certificates' },
    { id: 'sf-m4', title: 'Distribute stationery kits', description: 'Provide 200 stationery kits including notebooks, pens, pencils, and geometry sets.', amount_locked: 25000, status: 'LOCKED', required_proof: 'Photo of kit distribution event with students and school stamp' },
  ],
  'pragati-path': [
    { id: 'pp-m1', title: 'Purchase 50 tablets', description: 'Procure 50 Android tablets pre-loaded with educational apps for students.', amount_locked: 50000, status: 'UNLOCKED', required_proof: 'Invoice + unboxing photo showing tablet serial numbers' },
    { id: 'pp-m2', title: 'Set up digital classroom infrastructure', description: 'Install projectors, WiFi routers, and charging stations in 2 classrooms.', amount_locked: 50000, status: 'LOCKED', required_proof: 'Photo of fully functional digital classroom with students' },
    { id: 'pp-m3', title: 'Teacher training on digital tools', description: 'Training session for 20 teachers on using Google Classroom, Khan Academy, and tablets.', amount_locked: 50000, status: 'LOCKED', required_proof: 'Photo of training session with attendance sheet visible' },
    { id: 'pp-m4', title: 'Student digital literacy program', description: 'Conduct 4 weeks of digital literacy workshops for students, certify 200 students.', amount_locked: 50000, status: 'LOCKED', required_proof: 'Photo of certificate distribution ceremony' },
  ],
  'annamayya-trust': [
    { id: 'at-m1', title: 'Procure monthly ration supplies', description: 'Purchase rice, lentils, oil, and essential groceries for 500 families for one month.', amount_locked: 20000, status: 'UNLOCKED', required_proof: 'Photo of procured supplies in storage with weighing slips' },
    { id: 'at-m2', title: 'Set up community kitchen equipment', description: 'Install large cooking vessels, gas connections, and food-grade storage containers.', amount_locked: 20000, status: 'UNLOCKED', required_proof: 'Photo of operational kitchen setup with equipment labeled' },
    { id: 'at-m3', title: 'Feed 500 homeless for one month', description: 'Daily meal service at identified shelters, 500 meals per day for 30 days.', amount_locked: 20000, status: 'LOCKED', required_proof: 'Daily log photos + final headcount certificate from shelter' },
    { id: 'at-m4', title: 'Expand to second location', description: 'Establish a second kitchen site and begin serving meals in an underserved locality.', amount_locked: 20000, status: 'LOCKED', required_proof: 'Photo of the new site operational with signage and first meal being served' },
  ],
  'nourish-the-nation': [
    { id: 'nn-m1', title: 'Procure first batch of ration kits', description: 'Purchase and assemble 100 monthly ration kits for migrant families.', amount_locked: 37500, status: 'UNLOCKED', required_proof: 'Photo of assembled kits with list of contents visible' },
    { id: 'nn-m2', title: 'Identify and register 100 migrant families', description: 'Survey, document, and register 100 migrant worker families in the distribution program.', amount_locked: 37500, status: 'LOCKED', required_proof: 'Anonymized list of registered families with government ID verification slips' },
    { id: 'nn-m3', title: 'Monthly distribution drive 1', description: 'First distribution event—hand over 100 ration kits to registered families.', amount_locked: 37500, status: 'LOCKED', required_proof: 'Photo of distribution event with families receiving kits and signed acknowledgments' },
    { id: 'nn-m4', title: 'Monthly distribution drive 2', description: 'Second month distribution to the same 100 families, ensuring continuity.', amount_locked: 37500, status: 'LOCKED', required_proof: 'Photo of second distribution with updated beneficiary list' },
  ],
  'aarogya-health-mission': [
    { id: 'ahm-m1', title: 'Purchase mobile medical equipment', description: 'Buy diagnostic equipment: BP monitors, glucometers, stethoscopes, and a portable ultrasound unit.', amount_locked: 75000, status: 'UNLOCKED', required_proof: 'Invoice and photo of all equipment with serial numbers' },
    { id: 'ahm-m2', title: 'Conduct first medical camp', description: 'On-site health camp in a remote village, targeting 300 patients per camp day.', amount_locked: 75000, status: 'UNLOCKED', required_proof: 'Camp photo with patient sign-in register and doctor certifications visible' },
    { id: 'ahm-m3', title: 'Provide medicines for 300 patients', description: 'Distribute prescribed medicines and vitamins to 300 identified patients.', amount_locked: 75000, status: 'LOCKED', required_proof: 'Photo of medicine distribution with prescription logs' },
    { id: 'ahm-m4', title: 'Train community health workers', description: 'Train 20 local women as community health workers (CHWs) to follow up on patients.', amount_locked: 75000, status: 'LOCKED', required_proof: 'Training photo with certificates issued by accredited health body' },
  ],
  'vriksh-protectors': [
    { id: 'vp-m1', title: 'Procure 500 native saplings', description: 'Purchase 500 native tree saplings (Peepal, Neem, Fruit trees) from certified nurseries.', amount_locked: 12500, status: 'UNLOCKED', required_proof: 'Photo of saplings with nursery bill and species labels visible' },
    { id: 'vp-m2', title: 'Identify and prepare planting sites', description: 'Survey and soil-test 5 degraded land plots, prepare them for planting.', amount_locked: 12500, status: 'LOCKED', required_proof: 'GPS-tagged photo of each site with soil preparation visible' },
    { id: 'vp-m3', title: 'Community planting drive', description: 'Organize a single-day mass planting event with 50+ volunteers.', amount_locked: 12500, status: 'LOCKED', required_proof: 'Photo of planting event with volunteer count and saplings planted' },
    { id: 'vp-m4', title: '3 month maintenance and survival check', description: 'After 3 months, assess sapling survival rate. Target: 80% survival.', amount_locked: 12500, status: 'LOCKED', required_proof: 'Photo of surviving saplings with GPS match to original planting site' },
  ],
};
